### ISSUE TITLE
Hanshell can not create process

### ISSUE THREAD

**Issue by kas0n** [blackarrowsec/redteam-research#4]
The current user is "DefaultAppPool" and i can get other tokens, but i cannot get response when i use other tokens to create process with Hanshell
![image](https://user-images.githubusercontent.com/42311185/199007445-d814a8ad-d2f0-41f9-bf64-22e20a90a586.png)

![image](https://user-images.githubusercontent.com/42311185/199007519-04476455-211a-4a5a-876c-fa8ea95b46c8.png)

**Comment by Kudaes** [comment]
Hi @kas0n,

May you please download the shell with the latest commit and try again?
If it keeps failing, may you execute any command redirecting the ouput to a text file (something like "cmd.exe /C echo %username% > somefile.txt")?. This way we can check if the process is actually being spawned or not. 

Btw, in the first input field you should insert the file to execute, by default c:\windows\system32\cmd.exe.

**Comment by kas0n** [comment]
Thanks for replay. I tried the new shell, but still not work.I checked it with Process Hacker.

![Snipaste_2022-11-03_19-48-16](https://user-images.githubusercontent.com/42311185/199714335-30a12703-8ba2-425c-878b-dec830be8653.png)

And a strange question. I noticed that the shell can sometime spawn a process,but it  then crashed suddenly.

Most of the time , it can not spawn a process.

![error](https://user-images.githubusercontent.com/42311185/199714428-6fe154d3-4d63-4aa5-904f-6b7b5ad50c0e.gif)

**Comment by Kudaes** [comment]
As you can see from Process Hacker, the token of the user Administrator is an impersonation token. In order to spawn the new process, we are making a call to CreateProcessWithToken, and according to the official documentation (https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-createprocesswithtokenw) this functions is expecting a primary token. This is probably why you are getting that weird behaviour.

If you want to try to fix it, make a call to DuplicateTokenEx passing the token handle and specifying TokenPrimary as the TokenType. That should return a valid primary token that you can pass then to CreateProcessWithToken to spawn the cmd and hopelly this will resolve the issue.

I'd like to know the outcome, so if you end up giving it a try let me know how the story ends ;)

**Comment by kas0n** [comment]
I am inexperienced in coding with c# 😭. Sorry for that , but the code has already done what you said .
https://github.com/blackarrowsec/redteam-research/blob/508aaab4ed4b964fd0c030ce9e4e0ec04cace49f/Hanshell/Hanshell.aspx#L293

I am confused now ...

**Comment by Kudaes** [comment]
haha can you believe that I am the one who actually coded that? It's clear that it has been a very long week...

Now I am confused as well, i don't know where that behavior is coming from, but I will investigate it a little bit more when I have some spare time. 

Just to know, have you changed any settings of the Administrator user? Any particular configuration on your IIS site that I should be aware of?

**Comment by Kudaes** [comment]
Hi @kas0n,

 We've done some research on your issue, and it seems to be related to how Windows workstations work. Could you try the new version of the shell to see if it works properly now? For me, it looks like replacing CreateProcessWithToken with CreateProcessAsUser has resolved the issue, but I'd like to know if this works for you too.

Thank you.

**Comment by Kudaes** [comment]
Hi @kas0n,

We've done some research on your issue, and it seems to be related to how Windows workstations work. Could you try the new version of the shell to see if it works properly now? For me, it looks like replacing CreateProcessWithToken with CreateProcessAsUser has resolved the issue, but I'd like to know if this works for you too.

Thank you.

**Comment by Kudaes** [comment]
Glad to heard that :) 

Im closing the issue, but do not hesitate to reach us again if you need help with anything else ;)
